[context.production]
  publish = "docs"
  command = "hugo"
  environment = {HUGO_VERSION = "0.82.0"}

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture --cleanDestinationDir --destination docs-drafts"
  publish = "docs-drafts"
  environment = {HUGO_VERSION = "0.82.0"}
  

[context.branch-deploy]
  command = "hugo --buildFuture"
  environment = {HUGO_VERSION = "0.82.0"}